format = """
[ ┌─](#2346bc)\
[](bg:#100e1f fg:#100e1f)\
$directory\
[](bg:#100e1f fg:#100e1f)\
$git_branch\
$git_status\
$git_metrics\
[](bg:#100e1f fg:#100e1f)\
$c\
$lua\
[](#100e1f)\
$fill\
[](#100e1f)\
$time\
$cmd_duration\
[](bg:#100e1f fg:#100e1f) \
\n$character\
"""

[directory]
style = "fg:#75C9E9 bg:#100e1f"
format = "[ $path]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
"Template" = " "
"Puplic" = "󱖜 "
"Videos" = " "
"git" = " "
".scripts" = " "
"mnt" = "󰋊 "

[git_branch]
symbol = " "
style = "fg:green bg:#100e1f "
format = '[ $symbol $branch]($style)'

[git_status]
format = '([\[$all_status$ahead_behind\] ]($style))'
style = "fg:green bg:#100e1f"
conflicted = '󰈸'
up_to_date = '✓ '
untracked = '󰮀 '
stashed = ' '
modified = ' '
staged = '[++\($count\)](fg:green bg:#100e1f)'
renamed = '󰙏 '
deleted = ' '
ahead = '⇡${count}'
diverged = '⇕⇡${ahead_count}⇣${behind_count}'
behind = '⇣${count}'

[git_metrics]
disabled = false
added_style = 'fg:#2346bc bg:#100e1f'
deleted_style = 'fg:#2346bc bg:#100e1f '
format = '[+$added]($added_style)[|-$deleted ]($deleted_style)'

[git_state]
disabled = false
format = '[\($state( $progress_current of $progress_total)\)]($style)'
cherry_pick = '[ PICKING](#d91b4f)'

[c]
format = '[ $symbol($version(-$name)) ($style)]'
symbol = " "
style = "fg:#fff5ca bg:#100e1f"

[lua]
format = '[ $symbol|$version ]($style)'
symbol = " "
style = "fg:#fff5ca bg:#100e1f"

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#100e1f"
format = '[[  $time ](fg:#e3e7ed bg:#100e1f)]($style)'

[cmd_duration]
format = "[ $duration]($style)"
style = "fg:#48c9c4 bg:#100e1f"

[character]
success_symbol = "[ └─>](#2346bc)"
error_symbol = "[ └─>](#d91b4f)"
